export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_MANUFACTURER = 'CREATE_MANUFACTURER';
export const FETCH_MANUFACTURERS = 'FETCH_MANUFACTURERS';
export const FETCH_MANUFACTURER = 'FETCH_MANUFACTURER';
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';
export const EDIT_MANUFACTURER = 'EDIT_MANUFACTURER';

export const CREATE_CARMODEL = 'CREATE_CARMODEL';
export const FETCH_CARMODELS = 'FETCH_CARMODELS';
export const FETCH_CARMODELS_BY_MANUFACTURER = 'FETCH_CARMODELS_BY_MANUFACTURER';
export const FETCH_CARMODEL = 'FETCH_CARMODEL';
export const DELETE_CARMODEL = 'DELETE_CARMODEL';
export const EDIT_CARMODEL = 'EDIT_CARMODEL';
