export const SAFETY_EQUIPMENTS_SELECTIONS = {
    1: { abbrev:"ABS", propertiesName: "antilockBrakingSystem", chineseName:"防鎖死煞車系統", 
        displayName: "ABS", defaultSelected: false, shouldDisplay: false },
    2: { abbrev:"ASR", propertiesName: "accelerationStabilityRetainer", chineseName:"循跡防滑控制系統", 
        displayName: "ASR", defaultSelected: false, shouldDisplay: false },
    3: { abbrev:"EBD", propertiesName: "electronicBrakeforceDistribution", chineseName:"電子煞車力道分配系統", 
        displayName: "EBD", defaultSelected: false, shouldDisplay: false },
    4: { abbrev:"BAS", propertiesName: "brakeAssistSystem", chineseName:"煞車力道輔助系統", 
        displayName: "BAS", defaultSelected: false, shouldDisplay: false },
    5: { abbrev:"ESP", propertiesName: "electronicStabilityProgram", chineseName:"車身動態穩定系統", 
        displayName: "ESP/ESC", defaultSelected: true, shouldDisplay: true },
    6: { abbrev:"cc", propertiesName: "cruiseControl", chineseName:"定速", 
        displayName: "定速", defaultSelected: true, shouldDisplay: true },
    7: { abbrev:"ACC", propertiesName: "adaptiveCruiseControl", chineseName:"主動車距巡航控制系統", 
        displayName: "ACC", defaultSelected: true, shouldDisplay: true },
    8: { abbrev:"FCW", propertiesName: "forwardCollisionWarning", chineseName:"前方碰撞警示", 
        displayName: "FCW", defaultSelected: true, shouldDisplay: true },
    9: { abbrev:"AEB", propertiesName: "automaticEmergencyBraking", chineseName:"自動緊急煞車", 
        displayName: "AEB", defaultSelected: true, shouldDisplay: true },
    10: { abbrev:"LDW", propertiesName: "laneDepartureWarning", chineseName:"車道偏離警示", 
        displayName: "車偏警示", defaultSelected: true, shouldDisplay: true },
    11: { abbrev:"LDR", propertiesName: "laneDepartureRevise", chineseName:"車道偏離修正", 
        displayName: "車偏修正", defaultSelected: true, shouldDisplay: true },
    12: { abbrev:"LKA", propertiesName: "laneKeepingAssistance", chineseName:"車道維持", 
        displayName: "車道維持", defaultSelected: true, shouldDisplay: true },
    13: { abbrev:"RCTA", propertiesName: "rearCrossTrafficWarning", chineseName:"後方車側警示", 
        displayName: "RCTA", defaultSelected: true, shouldDisplay: true },
    14: { abbrev:"BSW", propertiesName: "blindSpotWarning", chineseName:"盲點偵測警示", 
        displayName: "盲點", defaultSelected: true, shouldDisplay: true },
    15: { abbrev:"RAEB", propertiesName: "reverseAutomaticEmergencyBraking", chineseName:"後方車流自動煞車", 
        displayName: "後AEB", defaultSelected: false, shouldDisplay: true },
    16: { abbrev:"HSA", propertiesName: "hillStartAssis", chineseName:"斜坡起步輔助", 
        displayName: "上坡輔助", defaultSelected: true, shouldDisplay: true },
    17: { abbrev:"HDC", propertiesName: "hillDescentControl", chineseName:"陡坡緩降系統", 
        displayName: "下坡輔助", defaultSelected: false, shouldDisplay: true },
    18: { abbrev:"AirBagNumbers", propertiesName: "airBagNumbers", chineseName:"安全氣囊", 
        displayName: "氣囊六顆以上", defaultSelected: true, shouldDisplay: true },
    19: { abbrev:"ISOFIX", propertiesName: "isofix", chineseName:"ISOFIX", 
        displayName: "ISOFIX", defaultSelected: true, shouldDisplay: true },
    20: { abbrev:"APA", propertiesName: "activeParkingAssistance", chineseName:"自動停車", 
        displayName: "自動停車", defaultSelected: false, shouldDisplay: true },
    21: { abbrev:"surroundViewCamera", propertiesName: "surroundViewCamera", chineseName:"環景", 
        displayName: "環景", defaultSelected: false, shouldDisplay: true },
    22: { abbrev:"rearViewCamera", propertiesName: "rearViewCamera", chineseName:"倒車顯影", 
        displayName: "倒車顯影", defaultSelected: false, shouldDisplay: true }
    // {/* IIHS iihsDescription */}
    // {/* NCAP ncapDescription */}
};